# docker-compose.yml

version: '3.8'
services:
  postgres:
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_DB=taskdb
      - POSTGRES_USER=femitj
      - POSTGRES_PASSWORD=supersonic
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:
